/**
 * UP District → Block mapping (demo data)
 * Each district lists its development blocks.
 */
export const DISTRICT_BLOCKS: Record<string, string[]> = {
  "Agra":               ["Achhnera", "Bah", "Barauli Ahir", "Etmadpur", "Fatehabad", "Jagner", "Khandauli", "Kheragarh", "Pinahat", "Saidpur", "St. Johns Road"],
  "Aligarh":            ["Atrauli", "Bijauli", "Chandaus", "Dhanipur", "Gabhana", "Iglas", "Jawan", "Khair", "Lodha", "Mursan", "Tappal"],
  "Ambedkar Nagar":     ["Akbarpur", "Allapur", "Baskhari", "Bhiti", "Jalalpur", "Katehari", "Ram Nagar", "Tanda"],
  "Amethi":             ["Amethi", "Bazar Shukul", "Bhendua", "Gauriganj", "Jagdishpur", "Jahangirganj", "Sangrampur", "Shahgarh"],
  "Amroha":             ["Amroha", "Dhanaura", "Gajraula", "Hasanpur", "Joya", "Naugawan Sadat"],
  "Auraiya":            ["Auraiya", "Ajitmal", "Bidhuna", "Bhagyanagar", "Dibiyapur", "Sahar"],
  "Ayodhya":            ["Bikapur", "Haringtonganj", "Haveli", "Milkipur", "Maya Bazar", "Rudauli", "Sohawal"],
  "Azamgarh":           ["Atraulia", "Azamgarh", "Bilariyaganj", "Jahanaganj", "Lalganj", "Mehnagar", "Mirzapur", "Muhammadpur", "Phulpur", "Raunapar", "Tarwa"],
  "Badaun":             ["Alapur", "Asafpur", "Bahamrooli", "Bisauli", "Chandpur", "Dataganj", "Kakrala", "Samrer", "Shekhupur", "Ughaiti", "Wahidpur"],
  "Budaun":             ["Alapur", "Asafpur", "Bahamrooli", "Bisauli", "Chandpur", "Dataganj", "Kakrala", "Samrer", "Shekhupur", "Ughaiti", "Wahidpur"],
  "Baghpat":            ["Baghpat", "Baraut", "Chhaprauli", "Khekra", "Pilana", "Sindhauli"],
  "Bahraich":           ["Balha", "Bisinda", "Chittaura", "Fakharpur", "Jarwal", "Kaiserganj", "Mahasi", "Mihinpurwa", "Nawabganj", "Payagpur", "Risia", "Tejwapur"],
  "Ballia":             ["Ballia", "Bansdih", "Bairiya", "Belhari", "Dubhar", "Garwar", "Hanumanganj", "Maniyar", "Murli Chhapra", "Nagra", "Narhi", "Pandah", "Reoti", "Siar", "Sohanv"],
  "Balrampur":          ["Balrampur", "Gaisadi", "Hauzpur", "Pachperwa", "Shravasti", "Tulsipur", "Utraula"],
  "Banda":              ["Atarra", "Baberu", "Banda", "Bisanda", "Jaspura", "Kamasin", "Mahuva", "Naraini", "Pailani", "Tindwari"],
  "Barabanki":          ["Dariyabad", "Dewa", "Fatehpur", "Haidergarh", "Nawabganj", "Ram Sanehi Ghat", "Ramnagar", "Sirauli"],
  "Bareilly":           ["Aonla", "Baheri", "Bithri Chainpur", "Faridpur", "Fatehganj", "Meergunj", "Mirganj", "Nawabganj", "Richha", "Shergarh"],
  "Basti":              ["Basti Sadar", "Harraiya", "Kaptanganj", "Kudaraha", "Ramnagar", "Rudhauli", "Saunapur"],
  "Bijnor":             ["Afzalgarh", "Chandpur", "Dhampur", "Haldaur", "Jalilpur", "Kiratpur", "Kotwali", "Mandawar", "Najibabad", "Nazimabad", "Nehtaur", "Nurpur", "Seohara", "Shikarpur"],
  "Bulandshahr":        ["Agauta", "Anupshahr", "Bulandshahr", "Danpur", "Dibai", "Gulaothi", "Jahangirabad", "Khurja", "Siyana", "Syana"],
  "Chandauli":          ["Chandauli", "Chahaniya", "Chakia", "Dhanapur", "Niyamatabad", "Sahadeo", "Sakaldiha", "Shakteshgarh"],
  "Chitrakoot":         ["Chitrakoot", "Karvi", "Manikpur", "Pahadi", "Rajapur"],
  "Deoria":             ["Barhaj", "Bhatni", "Bhatapar Rani", "Desai", "Deoria", "Gauribazar", "Kaptanganj", "Lar", "Rampur Karkhana", "Rudrapur", "Salempur", "Tarkulwa"],
  "Etah":               ["Aliganj", "Awagarh", "Etah", "Jalesar", "Marhara", "Patiyali"],
  "Etawah":             ["Basrehar", "Barhpur", "Bharthana", "Etawah", "Jaswantnagar", "Saifai"],
  "Farrukhabad":        ["Ambiapur", "Fatehgarh", "Kayamganj", "Kaimganj", "Moh Mohammadabad", "Shamsabad"],
  "Fatehpur":           ["Asothar", "Bindki", "Dhata", "Fatehpur", "Hathgaon", "Khaga", "Malwan", "Teliyani", "Vijayipur"],
  "Firozabad":          ["Araon", "Firozabad", "Jasrana", "Narkhi", "Shikohabad", "Sirsaganj", "Tundla"],
  "Gautam Buddha Nagar":["Bisrakh", "Dadri", "Dankaur", "Jewar"],
  "Ghaziabad":          ["Bhojpur", "Bhopura", "Hapur", "Loni", "Modinagar", "Muradnagar", "Razapur"],
  "Ghazipur":           ["Bhanvarkol", "Bhadaura", "Ghazipur", "Jangipur", "Karanda", "Kasimabad", "Mahuar", "Mansoor", "Mohammadabad", "Sadat", "Saidpur", "Zamania"],
  "Gonda":              ["Babalpur", "Colonelganj", "Dharopur", "Itiyathok", "Karnailganj", "Khajani", "Manha", "Nawabganj", "Paraspur", "Tarabganj", "Utraula"],
  "Gorakhpur":          ["Bansgaon", "Bhathat", "Bhagtapur", "Campierganj", "Chauri Chaura", "Chargawan", "Gagha", "Gola", "Jungle Kaudia", "Khajni", "Khorabar", "Pipraich", "Sahjanwa", "Uruwa"],
  "Hamirpur":           ["Hamirpur", "Kurara", "Maudaha", "Muskara", "Rath", "Sumerpur"],
  "Hapur":              ["Dhaulana", "Garhmukteshwar", "Hapur", "Simbhavali"],
  "Hardoi":             ["Ahirori", "Bilgram", "Hardoi", "Kachhauna", "Kotra", "Madhoganj", "Mallawan", "Pata", "Sandi", "Sandila", "Shahabad", "Surauna", "Tadiyawan"],
  "Hathras":            ["Hathras", "Mursan", "Sahpau", "Sadabad", "Sikandra Rao"],
  "Jalaun":             ["Jalaun", "Kadaura", "Konch", "Madhaugarh", "Nadigaon", "Orai", "Rampura"],
  "Jaunpur":            ["Badlapur", "Baksha", "Barsathi", "Dobhi", "Jaunpur", "Kerakat", "Machhali Shahar", "Mungra Badshahpur", "Shahganj", "Sirkoni", "Sujanganj", "Suithakalan"],
  "Jhansi":             ["Babina", "Badagaon", "Baleh", "Bangra", "Chirgaon", "Gursarai", "Jhansi", "Mauranipur", "Moth", "Parichha", "Rajpur"],
  "Kannauj":            ["Chhibramau", "Gursahaiganj", "Haseran", "Kannauj", "Sakaldiha", "Talgram", "Umarda"],
  "Kanpur Dehat":       ["Akbarpur", "Amroudha", "Derapur", "Jhinjhak", "Maitha", "Rasulabad", "Rasoolabad", "Sanigawan"],
  "Kanpur Nagar":       ["Armapur", "Bilhaur", "Chaubepur", "Ghatampur", "Kalyanpur", "Kanhpur", "Vidhnu"],
  "Kasganj":            ["Amanpur", "Ganjdundwara", "Kasganj", "Patiyali", "Sidhpura", "Soron"],
  "Kaushambi":          ["Chayal", "Kara", "Manjhanpur", "Saini", "Sirathu"],
  "Kushinagar":         ["Dudhi", "Hata", "Khadda", "Kushinagar", "Nebua Naurangia", "Padrauna", "Ramkola", "Sewarhi", "Sukrauli", "Tamkuhi Raj", "Vishunpura"],
  "Lakhimpur Kheri":    ["Behjam", "Bijua", "Dhaurhara", "Gola Gokarna Nath", "Isanagar", "Lakhimpur", "Mitauli", "Mohammed", "Nighasan", "Pasgawan", "Palia", "Phulbehad", "Ramnagar"],
  "Lalitpur":           ["Jakhaura", "Lalitpur", "Mahroni", "Mandawara", "Mehrauni", "Talbehat"],
  "Lucknow":            ["Bakshi Ka Talab", "Lucknow Cant", "Mahona", "Mal", "Malhour", "Mohanlalganj", "Sarojini Nagar"],
  "Maharajganj":        ["Bridgmanganj", "Dhani", "Farenda", "Ghughli", "Lakhi", "Maharajganj", "Nautanwa", "Nichlaul", "Paniyara", "Partawal", "Siswa Bazar"],
  "Mahoba":             ["Charkhari", "Kabrai", "Kulpahar", "Mahoba", "Panwari"],
  "Mainpuri":           ["Bhogaon", "Ghiror", "Kuraoli", "Mainpuri", "Kishni"],
  "Mathura":            ["Baldeo", "Chhata", "Farah", "Goverdhan", "Mahavan", "Mat", "Mathura", "Mant", "Nandgaon", "Naujheel", "Raya"],
  "Mau":                ["Dohariya", "Dohrighat", "Ghosi", "Kopaganj", "Mau", "Mohammadabad Gohna", "Phefna", "Ratnapur"],
  "Meerut":             ["Daurala", "Hapur", "Inchaura", "Kithore", "Mawana", "Meerut", "Parikshitgarh", "Rajpura", "Rohta", "Sardhana"],
  "Mirzapur":           ["Ahraura", "Chhanbey", "Chunar", "Dehat Area", "Jamalpur", "Kon", "Lalganj", "Marihan", "Mirzapur", "Narayanpur", "Naigarhi", "Pahari", "Rajgarh", "Sikhar"],
  "Moradabad":          ["Bahjoi", "Bilari", "Cundarki", "Datianaganj", "Moradabad", "Sambhal", "Thakurdwara"],
  "Muzaffarnagar":      ["Baghara", "Budhana", "Charthawal", "Jansath", "Kandhla", "Khatauli", "Miranpur", "Muzaffarnagar", "Purkazi", "Shahpur"],
  "Pilibhit":           ["Amariya", "Barkhera", "Bisalpur", "Gajraula", "Laloria Buzurg", "Marori", "Puranpur"],
  "Pratapgarh":         ["Aspur Deosara", "Babaganj", "Dhanupur", "Gaura", "Kalakankar", "Kunda", "Lakshmanganj", "Laxmanpur", "Manadhata", "Mandhata", "Patti", "Rampur Khas", "Sandwa Chandrika", "Sangrampur", "Shivgarh"],
  "Prayagraj":          ["Baharia", "Bahadurpur", "Bara", "Chaka", "Dhanupur", "Holagarh", "Karchana", "Kaudihar", "Koraon", "Manda", "Meja", "Phulpur", "Pratappur", "Shankargarh", "Soraon", "Srinivaspuri", "Totiari", "Handia"],
  "Raebareli":          ["Bachrawan", "Dalmau", "Dih", "Gauramau", "Harchandpur", "Jagatpur", "Lalganj", "Mahrajganj", "Raebareli", "Sareni", "Shivgarh", "Salon", "Tiloi", "Unchahar"],
  "Rampur":             ["Bilaspur", "Chamraua", "Milak", "Rampur", "Shahabad", "Suar", "Tanda"],
  "Saharanpur":         ["Behat", "Deoband", "Gangoh", "Muzaffarabad", "Nakur", "Nanauta", "Rampur Maniharan", "Saharanpur", "Sarsawa"],
  "Sambhal":            ["Asmaoli", "Bahjoi", "Chandausi", "Gunnaur", "Sambhal"],
  "Sant Kabir Nagar":   ["Baghauli", "Bhanwapur", "Dhanghata", "Hainsar Bazar", "Khalilabad", "Mehdawal", "Naugarh", "Semriawa"],
  "Shahjahanpur":       ["Banda", "Dadrol", "Jalalabad", "Kant", "Khutar", "Mirzapur", "Nigohi", "Powayan", "Shahjahanpur", "Sindhauli", "Tilhar"],
  "Shamli":             ["Kairana", "Shamli", "Thanabawan", "Un"],
  "Shravasti":          ["Bhinga", "Gilaula", "Hariharapur Rani", "Jamunaha", "Sirsia"],
  "Siddharthnagar":     ["Bhanwapur", "Bansi", "Birdpur", "Domariyaganj", "Itwa", "Jogia", "Khesraha", "Mitwal", "Naugarh", "Shohratgarh"],
  "Sitapur":            ["Biswan", "Gondia", "Hargaon", "Laharpur", "Mahmudabad", "Machhlishahr", "Misrikh", "Parsendi", "Ramkot", "Reusa", "Sakran", "Sidhauli"],
  "Sonbhadra":          ["Babhani", "Chopan", "Dudhi", "Ghorawal", "Kon", "Myorpur", "Nagwa", "Robertsganj"],
  "Sultanpur":          ["Akhandnagar", "Bhadaura", "Caursath", "Dostpur", "Dubeypur", "Dhanpatganj", "Kadipur", "Kurwar", "Lambhua", "Musafirkhana", "Sultanpur"],
  "Unnao":              ["Asoha", "Bangarmau", "Bighapur", "Fatehpur Chaurasi", "Hasanganj", "Hilauli", "Maurawan", "Nawabganj", "Purwa", "Safipur", "Sikandarpur Sarosi", "Sikandrabad"],
  "Varanasi":           ["Arajiline", "Badagaon", "Baragaon", "Chiraigaon", "Cholapur", "Harahua", "Kashi Vidyapeeth", "Pindra", "Sewapuri"],
};

export const ALL_UP_DISTRICTS = Object.keys(DISTRICT_BLOCKS).sort();

export function getBlocksForDistrict(district: string): string[] {
  return DISTRICT_BLOCKS[district] ?? [];
}
